name: Auto Create PR to staging from feature branch

on:
  pull_request:
    types: [opened]
    branches: [develop]

jobs:
  create_staging_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create and push -stg branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@example.com"
          git fetch origin staging:staging
          git checkout -b ${{ github.event.pull_request.head.ref }}-stg
          git merge --strategy=ort staging --allow-unrelated-histories
          git push origin ${{ github.event.pull_request.head.ref }}-stg
      - name: Add Label
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: 'develop, pending'
      - name: Set Assignee
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-assignee ${{ github.event.pull_request.user.login }}
      - name: Prepare PR Body
        run: |
          echo 'PR_BODY<<EOF' >> $GITHUB_ENV
          echo "Automated PR. Original PR is #${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "---" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "${{ github.event.pull_request.body }}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Create PR to staging
        uses: repo-sync/pull-request@v2
        with:
          source_branch: '${{ github.event.pull_request.head.ref }}-stg'
          destination_branch: staging
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: staging
          pr_assignee: ${{ github.event.pull_request.user.login }}
          pr_title: '${{ github.event.pull_request.title }}(staging用)'
          pr_body: ${{ env.PR_BODY }}
