name: Auto Create PR to staging from feature branch

on:
  pull_request:
    types: [opened]
    branches:
      - develop

jobs:
  create_staging_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create PR to staging
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ github.head_ref }}
        destination_branch: "staging"
        pr_title: "${{ github.event.pull_request.title }}(staging用)"
        pr_body: "Automated PR. Original PR is ${{ github.event.pull_request.html_url }}"
        github_token: ${{ secrets.GITHUB_TOKEN }}
