name: Sync to -stg branch
on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'

jobs:
  sync-to-stg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Git and sync to -stg branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@example.com"
          original_branch=${GITHUB_REF#refs/heads/}
          stg_branch="${original_branch}-stg"
          git fetch origin $stg_branch:$stg_branch || { echo "$stg_branch does not exist, skipping."; exit 0; }

          git fetch origin $original_branch:$original_branch
          git checkout $stg_branch
          git branch -a
          git status
          git merge git merge --strategy=recursive $original_branch --allow-unrelated-histories
          git push origin $stg_branch
